# coding: utf8

NAME="name"
TYPE = 'type'
VALUE = 'value'
LINKS = 'links'
MEDIA_TYPE = 'media_type'
ITEM = 'item'
ITEM_MAIN = 'main'
EXTRACTOR = 'extractor'
BASE_URL = 'base_url'
PAGE_LINK = 'page_link'
DOC = 'doc'
RENDER = 'render'
OTHER_DOC = 'other'
ITEM_ID = 'id'
ITEM_LIST = 'list'
FORMAT = 'format'
META_LINK = '_meta_link'
META_ITEM = '_meta_item'
REFER_URL = '_refer_url'
SPIDER = '_spider'
LIST = 'list'
TIMESTAMP = 'timestamp'